/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IContractManager } from "./IContractManager";
export type { IRaffles } from "./IRaffles";
export type { IReferralManager } from "./IReferralManager";
export type { IStaking } from "./IStaking";
export type { ITeams } from "./ITeams";
