/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace ITeams {
  export type TeamPlanStruct = {
    teamPlanId: BigNumberish;
    subscriptionCost: BigNumberish;
    reward: BigNumberish;
    stakingThreshold: BigNumberish;
    teamSize: BigNumberish;
    stakingPlanId: BigNumberish;
    isActive: boolean;
  };

  export type TeamPlanStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    teamPlanId: BigNumber;
    subscriptionCost: BigNumber;
    reward: BigNumber;
    stakingThreshold: BigNumber;
    teamSize: BigNumber;
    stakingPlanId: BigNumber;
    isActive: boolean;
  };

  export type TeamStruct = {
    subscription: BigNumberish;
    teamsFilled: BigNumberish;
  };

  export type TeamStructOutput = [BigNumber, BigNumber] & {
    subscription: BigNumber;
    teamsFilled: BigNumber;
  };
}

export interface ITeamsInterface extends utils.Interface {
  functions: {
    "getActivePlans()": FunctionFragment;
    "getPlan(uint256)": FunctionFragment;
    "getPlans()": FunctionFragment;
    "getSufficientPlanIdByStakingAmount(uint256,uint256)": FunctionFragment;
    "getUserSubscription(address,uint256)": FunctionFragment;
    "getUserTeamMembers(address,uint256)": FunctionFragment;
    "hasAnySubscription(address)": FunctionFragment;
    "subscribe(uint256)": FunctionFragment;
    "tryToAddMember(uint256,address,address,uint256)": FunctionFragment;
    "userHasPlanSubscription(address,uint256)": FunctionFragment;
    "userHasSufficientStaking(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getActivePlans"
      | "getPlan"
      | "getPlans"
      | "getSufficientPlanIdByStakingAmount"
      | "getUserSubscription"
      | "getUserTeamMembers"
      | "hasAnySubscription"
      | "subscribe"
      | "tryToAddMember"
      | "userHasPlanSubscription"
      | "userHasSufficientStaking"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getActivePlans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPlans", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSufficientPlanIdByStakingAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubscription",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTeamMembers",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAnySubscription",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tryToAddMember",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userHasPlanSubscription",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userHasSufficientStaking",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getActivePlans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPlans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSufficientPlanIdByStakingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTeamMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAnySubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tryToAddMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userHasPlanSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userHasSufficientStaking",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITeams extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITeamsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getActivePlans(
      overrides?: CallOverrides
    ): Promise<[ITeams.TeamPlanStructOutput[]]>;

    getPlan(
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[ITeams.TeamPlanStructOutput]>;

    getPlans(
      overrides?: CallOverrides
    ): Promise<[ITeams.TeamPlanStructOutput[]]>;

    getSufficientPlanIdByStakingAmount(
      stakingPlanId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUserSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[ITeams.TeamStructOutput]>;

    getUserTeamMembers(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    hasAnySubscription(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    subscribe(
      planId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    tryToAddMember(
      stakingPlanId: BigNumberish,
      user: string,
      member: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userHasPlanSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    userHasSufficientStaking(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getActivePlans(
    overrides?: CallOverrides
  ): Promise<ITeams.TeamPlanStructOutput[]>;

  getPlan(
    planId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ITeams.TeamPlanStructOutput>;

  getPlans(overrides?: CallOverrides): Promise<ITeams.TeamPlanStructOutput[]>;

  getSufficientPlanIdByStakingAmount(
    stakingPlanId: BigNumberish,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserSubscription(
    user: string,
    planId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ITeams.TeamStructOutput>;

  getUserTeamMembers(
    user: string,
    planId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  hasAnySubscription(user: string, overrides?: CallOverrides): Promise<boolean>;

  subscribe(
    planId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  tryToAddMember(
    stakingPlanId: BigNumberish,
    user: string,
    member: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userHasPlanSubscription(
    user: string,
    planId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  userHasSufficientStaking(
    user: string,
    planId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getActivePlans(
      overrides?: CallOverrides
    ): Promise<ITeams.TeamPlanStructOutput[]>;

    getPlan(
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ITeams.TeamPlanStructOutput>;

    getPlans(overrides?: CallOverrides): Promise<ITeams.TeamPlanStructOutput[]>;

    getSufficientPlanIdByStakingAmount(
      stakingPlanId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ITeams.TeamStructOutput>;

    getUserTeamMembers(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    hasAnySubscription(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    subscribe(planId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    tryToAddMember(
      stakingPlanId: BigNumberish,
      user: string,
      member: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    userHasPlanSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    userHasSufficientStaking(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getActivePlans(overrides?: CallOverrides): Promise<BigNumber>;

    getPlan(
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPlans(overrides?: CallOverrides): Promise<BigNumber>;

    getSufficientPlanIdByStakingAmount(
      stakingPlanId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserTeamMembers(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasAnySubscription(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    subscribe(
      planId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    tryToAddMember(
      stakingPlanId: BigNumberish,
      user: string,
      member: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userHasPlanSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userHasSufficientStaking(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getActivePlans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPlan(
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPlans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSufficientPlanIdByStakingAmount(
      stakingPlanId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserTeamMembers(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasAnySubscription(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    subscribe(
      planId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    tryToAddMember(
      stakingPlanId: BigNumberish,
      user: string,
      member: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userHasPlanSubscription(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userHasSufficientStaking(
      user: string,
      planId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
